FROM lasote/conangcc72

ENV CONAN_GCC_VERSIONS 7
ENV CONAN_ARCHS x86_64

RUN conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
RUN conan remote add is https://api.bintray.com/conan/labviros/is                      
RUN pip install conan_package_tools conan --user --upgrade                                
